--2.customer behavior

--2.1how do repeat customers differ from one-time customers in customer
--share, order volume and revenue contribution?
select * from customers limit 5;
select * from orders limit 5;
select * from order_items limit 5;

with customer_summary as(
select
c.customer_unique_id,
count(distinct oi.order_id) as order_count,
sum(oi.price) as individual_revenue,
case when count(distinct oi.order_id) = 1
then 'one-time customer'
else 'repeat customer'
end as customer_type
from customers as c
join orders as o on c.customer_id = o.customer_id
join order_items as oi on o.order_id = oi.order_id
where o.order_status = 'delivered'
group by c.customer_unique_id
order by individual_revenue desc
)
select customer_type,
sum(order_count) as total_order_count,
count(customer_unique_id) as amount_of_customer,
round(100*(count(customer_unique_id)/sum(count(customer_unique_id))over()),2) as amount_share_by_type_percent,
round(sum(individual_revenue),2) as total_revenue_by_customer_type,
round(100*(sum(order_count)/sum(sum(order_count))over()),2)
as revenue_share_by_type_percent,
round(avg(individual_revenue),2) as average_revenue_by_customer_type
from customer_summary
group by customer_type;

--repeat customers only represent 3.00% of customers, 
--but contribute 6.14% of revenue. their average revenue per customer is 260.05,
--compared with 137.96 for one-time customers.


--what share of revenue is generated by the top customer segments?
with customer_summary as(
select
c.customer_unique_id,
count(distinct oi.order_id) as order_count,
sum(oi.price) as individual_revenue,
case when count(distinct oi.order_id) = 1
then 'one-time customer'
else 'repeat customer'
end as customer_type
from customers as c
join orders as o on c.customer_id = o.customer_id
join order_items as oi on o.order_id = oi.order_id
where o.order_status = 'delivered'
group by c.customer_unique_id
order by individual_revenue desc
),

customer_split5 as (
select customer_unique_id,
order_count,
individual_revenue,
ntile(5)over(order by individual_revenue desc) as  customer_class
from customer_summary
)

select
customer_class,
sum(individual_revenue) as total_revenue,
round(100*(sum(individual_revenue)/sum(sum(individual_revenue))over()),2)
as share_by_revenue
from customer_split5
group by customer_class
order by customer_class;
--Revenue is highly concentrated among high-value customers: 
--the top 20% of customers generated 56.62% of delivered-order revenue, 
--while the top 40% contributed 76.35%.

--how quickly do repeat customers make their first repeat purchase?
select * from orders limit 5

with customer_order as(
select
c.customer_unique_id,
o.order_id,
o.order_purchase_timestamp
from customers as c join orders as o
on c.customer_id = o.customer_id
where o.order_status = 'delivered'
),

previous_date_purchase as(
select
customer_unique_id,
order_purchase_timestamp,
order_id,
row_number()over(partition by customer_unique_id
order by order_purchase_timestamp) as purchase_number,
lag(order_purchase_timestamp)over(partition by customer_unique_id
order by order_purchase_timestamp) as previous_date
from customer_order
),

date_interval as(
select customer_unique_id,
purchase_number,
order_purchase_timestamp,
previous_date,
order_purchase_timestamp::date - previous_date::date as day_interval
from previous_date_purchase
where previous_date is not null
)

select
case
when day_interval <=30
then 'repeat within the month'
when day_interval <=90
then 'repeat within the season'
else 'over 90 days'
end as repurchase_interval,
count(*) as customer_count
from date_interval
where purchase_number = 2
group by repurchase_interval

-- first repeat purchases are concentrated in the earlier post-purchase period,
--although a meaningful share of repeat customers return only after more than 90 days.